export const projects = [
  {
    id: "1",
    title: "BariSathi (Smart Rental & Housing Solution)",
    shortDescription:
      "Full-stack web application connecting landlords, tenants, and an admin in a smart rental-housing platform.",
    description:
      "BariSathi is a full-stack web application connecting landlords, tenants, and an admin in a smart rental-housing platform. Landlords can post and manage rentals; tenants can browse, filter, and request rentals; admins oversee users and listings. Secure JWT auth, role-based access control, and Stripe payment options are built in.",
    images: [
      "/barisathi/home.png",
      "/barisathi/listings.png",
      "/barisathi/tenant-request.png",
      "/barisathi/admin-dashboard.png",
    ],
    coreFeatures: [
      "Landlords can post and manage rental listings",
      "Tenants can browse, filter, and request rentals",
      "Admins oversee users and listings",
      "Secure JWT authentication and role-based access",
      "Stripe payment integration",
      "Email notifications for approvals and payments",
    ],
    coreTechnology: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Radix UI",
      "Framer Motion",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "Zod",
      "JWT",
      "Stripe API",
    ],
    challengesFaced: [
      "Implementing secure JWT auth and role-based access control",
      "Integrating Stripe payment options",
      "Designing a robust admin dashboard",
      "Ensuring data consistency across user roles",
    ],
    futurePlans: [
      "Add advanced search filters for rentals",
      "Implement real-time chat between landlords and tenants",
      "Add property image gallery upload",
      "Enable multi-currency payment support",
    ],
    versionInfo: {
      "Next.js": "15.2.0",
      React: "^19.0.0",
      TypeScript: "^5",
      "Tailwind CSS": "4",
      "@stripe/stripe-js": "^7.0.0",
      "@stripe/react-stripe-js": "^3.6.0",
      "Node.js": "20",
    },
    liveLink: "https://barisathi.vercel.app",
    repositoryLink: "https://github.com/shahadathhs/barisathi",
  },
  {
    id: "2",
    title: "Bike Shop (E-commerce Application)",
    shortDescription:
      "Full-stack Bike Shop application enabling users to browse and purchase bicycles, with an admin dashboard for managing products, orders, and users.",
    description:
      "Bike Shop is a full-stack web application that enables users to browse and purchase bicycles, while providing administrators with a robust dashboard for managing products, orders, and users. It features secure JWT-based authentication, role-based access control, and Stripe integration for payment processing.",
    images: [
      "/bike-shop/home.png",
      "/bike-shop/products.png",
      "/bike-shop/admin-dashboard.png",
    ],
    coreFeatures: [
      "Responsive frontend with carousel banners and detailed product pages",
      "Secure user registration and login with JWT",
      "Role-based dashboards for customers and administrators",
      "Full CRUD operations for bike products",
      "Image uploads via Cloudinary",
      "Filtering, search, and pagination for product listings",
      "Stripe payment integration with real-time stock checks",
      "Order tracking and analytics in admin dashboard",
    ],
    coreTechnology: [
      "React",
      "TypeScript",
      "React Router v7",
      "Tailwind CSS",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "Zod",
      "JWT",
      "Stripe API",
      "Vite",
    ],
    challengesFaced: [
      "Implementing secure authentication and role-based access",
      "Integrating Stripe checkout with real-time stock validation",
      "Optimizing image uploads and pagination performance",
      "Designing comprehensive admin analytics dashboard",
    ],
    futurePlans: [
      "Add AI-driven product recommendations",
      "Integrate Notifications API for real-time notifications for order updates",
      "Add internationalization support",
    ],
    versionInfo: {
      React: "^19.0.0",
      TypeScript: "^5.7.2",
      "Tailwind CSS": "4.0.0",
      Vite: "^5.4.11",
      "Node.js": "20",
      Express: "^4.21.2",
      "Stripe API": "^17.6.0",
    },
    liveLink: "https://bike-shop-client-kappa.vercel.app",
    repositoryLink: "https://github.com/shahadathhs/bike-shop",
  },
  {
    id: "3",
    title: "Learning Management System",
    shortDescription:
      "An educational platform with course creation, enrollment, and progress tracking.",
    description:
      "This learning management system provides a comprehensive solution for educational institutions and online course creators. It includes features for course creation, student enrollment, content delivery, assessment, and progress tracking. The platform supports various content types, including video, text, quizzes, and assignments.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    coreFeatures: [
      "Course creation and management",
      "Student enrollment and access control",
      "Content delivery with multiple formats",
      "Assessment and grading",
      "Progress tracking and certificates",
      "Discussion forums and messaging",
    ],
    coreTechnology: [
      "React.js",
      "Firebase",
      "Cloud Functions",
      "Firestore",
      "Firebase Auth",
      "Cloud Storage",
    ],
    challengesFaced: [
      "Designing a scalable content delivery system",
      "Implementing secure assessment mechanisms",
      "Optimizing video streaming for various network conditions",
      "Creating an intuitive course creation interface",
    ],
    futurePlans: [
      "Add live classroom functionality",
      "Implement AI-powered learning path recommendations",
      "Develop mobile applications",
      "Add integration with popular video conferencing tools",
    ],
    versionInfo: {
      "React.js": "18.2.0",
      Firebase: "9.23.0",
      "Cloud Functions": "4.4.0",
      Firestore: "9.23.0",
      "Firebase Auth": "9.23.0",
      "Cloud Storage": "9.23.0",
    },
    liveLink: "https://example-lms.com",
    repositoryLink: "https://github.com/username/learning-management",
  },
  {
    id: "4",
    title: "Health Tracking Application",
    shortDescription:
      "A personal health monitoring app with fitness tracking, nutrition logging, and health insights.",
    description:
      "This health tracking application helps users monitor and improve their health and fitness. It includes features for tracking physical activity, logging nutrition intake, monitoring vital signs, and providing health insights. The app integrates with various fitness devices and provides personalized recommendations based on user data.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    coreFeatures: [
      "Activity tracking (steps, distance, calories)",
      "Nutrition logging and analysis",
      "Sleep monitoring and quality assessment",
      "Vital signs tracking (heart rate, blood pressure)",
      "Goal setting and progress tracking",
      "Health insights and recommendations",
    ],
    coreTechnology: [
      "React Native",
      "Redux",
      "Node.js",
      "MongoDB",
      "Express",
      "TensorFlow.js",
    ],
    challengesFaced: [
      "Integrating with various fitness devices and APIs",
      "Ensuring data privacy and security for health information",
      "Developing accurate algorithms for health insights",
      "Optimizing battery usage for continuous tracking",
    ],
    futurePlans: [
      "Add social features for community support",
      "Implement AI-powered health coaching",
      "Expand device integration options",
      "Add telehealth consultation features",
    ],
    versionInfo: {
      "React Native": "0.72.0",
      Redux: "4.2.1",
      "Node.js": "18.15.0",
      MongoDB: "6.0",
      Express: "4.18.2",
      "TensorFlow.js": "4.8.0",
    },
    liveLink: "https://example-healthapp.com",
    repositoryLink: "https://github.com/username/health-tracking",
  },
];
