export const projects = [
  {
    id: "1",
    title: "E-Commerce Platform",
    shortDescription:
      "A full-featured e-commerce platform with product management, cart, and checkout functionality.",
    description:
      "This e-commerce platform provides a comprehensive solution for online retailers. It includes product management, inventory tracking, user authentication, shopping cart functionality, and a secure checkout process. The platform is designed to be scalable and can handle a large number of products and concurrent users.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    coreFeatures: [
      "User authentication and authorization",
      "Product catalog with categories and search",
      "Shopping cart and wishlist functionality",
      "Secure checkout process",
      "Order tracking and history",
      "Admin dashboard for product and order management",
    ],
    coreTechnology: [
      "React.js",
      "Node.js",
      "Express",
      "MongoDB",
      "Redux",
      "Stripe API",
    ],
    challengesFaced: [
      "Implementing real-time inventory updates across multiple sessions",
      "Optimizing database queries for large product catalogs",
      "Ensuring secure payment processing",
      "Building a responsive design that works across all devices",
    ],
    futurePlans: [
      "Add AI-powered product recommendations",
      "Implement a vendor marketplace model",
      "Integrate with additional payment gateways",
      "Add advanced analytics for business insights",
    ],
    versionInfo: {
      React: "18.2.0",
      "Node.js": "18.15.0",
      Express: "4.18.2",
      MongoDB: "6.0",
      Redux: "4.2.1",
      "Stripe API": "12.0.0",
    },
    liveLink: "https://example-ecommerce.com",
    repositoryLink: "https://github.com/username/ecommerce-platform",
  },
  {
    id: "2",
    title: "Task Management System",
    shortDescription:
      "A collaborative task management system with real-time updates and team workspaces.",
    description:
      "This task management system helps teams organize and track their work efficiently. It provides features for creating tasks, assigning them to team members, setting deadlines, and tracking progress. The system supports real-time updates, so team members always have the latest information. It also includes reporting features to help managers monitor team performance.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    coreFeatures: [
      "Task creation and assignment",
      "Deadline setting and reminders",
      "Progress tracking with status updates",
      "Team workspaces and collaboration",
      "File attachments and comments",
      "Reporting and analytics",
    ],
    coreTechnology: [
      "Next.js",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Socket.io",
      "Chart.js",
    ],
    challengesFaced: [
      "Implementing real-time updates without performance degradation",
      "Designing an intuitive user interface for complex task relationships",
      "Managing database transactions for concurrent updates",
      "Ensuring data consistency across distributed systems",
    ],
    futurePlans: [
      "Add Gantt chart for project timeline visualization",
      "Implement AI-powered task prioritization",
      "Add time tracking functionality",
      "Develop mobile applications for iOS and Android",
    ],
    versionInfo: {
      "Next.js": "13.4.12",
      TypeScript: "5.1.6",
      Prisma: "4.16.2",
      PostgreSQL: "15.3",
      "Socket.io": "4.7.1",
      "Chart.js": "4.3.0",
    },
    liveLink: "https://example-taskmanager.com",
    repositoryLink: "https://github.com/username/task-management",
  },
  {
    id: "3",
    title: "Learning Management System",
    shortDescription:
      "An educational platform with course creation, enrollment, and progress tracking.",
    description:
      "This learning management system provides a comprehensive solution for educational institutions and online course creators. It includes features for course creation, student enrollment, content delivery, assessment, and progress tracking. The platform supports various content types, including video, text, quizzes, and assignments.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    coreFeatures: [
      "Course creation and management",
      "Student enrollment and access control",
      "Content delivery with multiple formats",
      "Assessment and grading",
      "Progress tracking and certificates",
      "Discussion forums and messaging",
    ],
    coreTechnology: [
      "React.js",
      "Firebase",
      "Cloud Functions",
      "Firestore",
      "Firebase Auth",
      "Cloud Storage",
    ],
    challengesFaced: [
      "Designing a scalable content delivery system",
      "Implementing secure assessment mechanisms",
      "Optimizing video streaming for various network conditions",
      "Creating an intuitive course creation interface",
    ],
    futurePlans: [
      "Add live classroom functionality",
      "Implement AI-powered learning path recommendations",
      "Develop mobile applications",
      "Add integration with popular video conferencing tools",
    ],
    versionInfo: {
      "React.js": "18.2.0",
      Firebase: "9.23.0",
      "Cloud Functions": "4.4.0",
      Firestore: "9.23.0",
      "Firebase Auth": "9.23.0",
      "Cloud Storage": "9.23.0",
    },
    liveLink: "https://example-lms.com",
    repositoryLink: "https://github.com/username/learning-management",
  },
  {
    id: "4",
    title: "Health Tracking Application",
    shortDescription:
      "A personal health monitoring app with fitness tracking, nutrition logging, and health insights.",
    description:
      "This health tracking application helps users monitor and improve their health and fitness. It includes features for tracking physical activity, logging nutrition intake, monitoring vital signs, and providing health insights. The app integrates with various fitness devices and provides personalized recommendations based on user data.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    coreFeatures: [
      "Activity tracking (steps, distance, calories)",
      "Nutrition logging and analysis",
      "Sleep monitoring and quality assessment",
      "Vital signs tracking (heart rate, blood pressure)",
      "Goal setting and progress tracking",
      "Health insights and recommendations",
    ],
    coreTechnology: [
      "React Native",
      "Redux",
      "Node.js",
      "MongoDB",
      "Express",
      "TensorFlow.js",
    ],
    challengesFaced: [
      "Integrating with various fitness devices and APIs",
      "Ensuring data privacy and security for health information",
      "Developing accurate algorithms for health insights",
      "Optimizing battery usage for continuous tracking",
    ],
    futurePlans: [
      "Add social features for community support",
      "Implement AI-powered health coaching",
      "Expand device integration options",
      "Add telehealth consultation features",
    ],
    versionInfo: {
      "React Native": "0.72.0",
      Redux: "4.2.1",
      "Node.js": "18.15.0",
      MongoDB: "6.0",
      Express: "4.18.2",
      "TensorFlow.js": "4.8.0",
    },
    liveLink: "https://example-healthapp.com",
    repositoryLink: "https://github.com/username/health-tracking",
  },
];
